version: "3.8"

services:
  client:
    image: node:latest
    container_name: timemanager_client
    entrypoint: /bin/sh
    ports:
      - "3030:3030"
    working_dir: /srv/app
    volumes:
      -   type: bind
          source: ./client
          target: /srv/app
    command: ["-c", "npm install && npm run dev"]

  server:
    image: elixir:latest
    container_name: timemanager_server
    entrypoint: /bin/sh
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    environment:
      MIX_ENV: dev
    depends_on:
      - db
    working_dir: /app
    command:
      - -c
      - |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
        mix ecto.migrate
        mix ecto.setup
        mix phx.server
    restart: always

  db:
    image: postgres:latest
    container_name: timemanager_db
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time_manager_dev