version: "3.8"

services:
  #elixir-phoenix:
  #image: elixir:latest
  #volumes:
  # - .:/app
  #restart: always
  #environment:
  #MIX_ENV: dev
  #command: [ "iex" ] # Interactive Elixir

  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    environment:
      MIX_ENV: dev
    depends_on:
      - db
    command:
      - /bin/sh
      - -c
      - |
        mix deps.get
        mix phx.server
    restart: always

  #client:
   # image: client
    #container_name: client
    #build:
     # context: ./client
      #dockerfile: Dockerfile
    #ports:
     # - "3030:3030"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time_manager_dev