version: "3.8"

services:
  server:
    build:
      context: ./server
    container_name: timemanager_server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
    environment:
      MIX_ENV: dev
    depends_on:
      - db
    command:
      - /bin/sh
      - -c
      - |
        mix deps.get
        mix ecto.migrate
        mix phx.server
    restart: always

  db:
    image: postgres:latest
    container_name: timemanager_db
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time_manager_dev