export enum Icons {
  IconAccountCircle = "icon-account-circle",
  IconAlarms = "icon-alarms",
  IconArrowLeft = "icon-arrow-left",
  IconArrowRight = "icon-arrow-right",
  IconClose = "icon-close",
  IconDangerTriangle = "icon-danger-triangle",
  IconDashboard = "icon-dashboard",
  IconDelete = "icon-delete",
  IconEdit = "icon-edit",
  IconEyeSharp = "icon-eye-sharp",
  IconLoader = "icon-loader",
  IconLogoutCircle = "icon-logout-circle",
  IconPowerOff = "icon-power-off",
  IconSettings = "icon-settings",
  IconTeams = "icon-teams",
  IconUsers = "icon-users",
  IconWorkingtimes = "icon-workingtimes",
}
