### Add Clocks (Check required)
POST http://localhost:4000/api/clocks/1

### Add Clocks (Check required)
POST http://localhost:4000/api/clocks/1
Content-Type: application/json

{
  "clock": {
  }
}

### Add clocks
POST http://localhost:4000/api/clocks/1
Content-Type: application/json

{
  "clock": {
    "time": "2023-10-24T16:13:18+0100",
    "status": true
  }
}

### Get by user id
GET http://localhost:4000/api/clocks/1

