### Add Clocks (Check required)
POST http://localhost:4000/api/clocks/1

### Add Clocks (Check required)
POST http://localhost:4000/api/clocks/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0aW1lX21hbmFnZXIiLCJleHAiOjE3MDExNjk5MzEsImlhdCI6MTY5ODc1MDczMSwiaXNzIjoidGltZV9tYW5hZ2VyIiwianRpIjoiYmEwZGQxZGEtZDg4NC00MDYyLWFjYWUtYTA2MmUyYTg4MWEyIiwibmJmIjoxNjk4NzUwNzMwLCJzdWIiOiIyMSIsInR5cCI6ImFjY2VzcyJ9.pQxCZlhfm735SblAzwob1kQXqMNKL234BxBE0cu5_Fajd3YbNLo77MK5IOOS3I2CmHgVXwMj5JU2FwQmn3Tm1w


{
  "clock": {
  }
}

### Add clocks
POST http://localhost:4000/api/clocks/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0aW1lX21hbmFnZXIiLCJleHAiOjE3MDExNjk5MzEsImlhdCI6MTY5ODc1MDczMSwiaXNzIjoidGltZV9tYW5hZ2VyIiwianRpIjoiYmEwZGQxZGEtZDg4NC00MDYyLWFjYWUtYTA2MmUyYTg4MWEyIiwibmJmIjoxNjk4NzUwNzMwLCJzdWIiOiIyMSIsInR5cCI6ImFjY2VzcyJ9.pQxCZlhfm735SblAzwob1kQXqMNKL234BxBE0cu5_Fajd3YbNLo77MK5IOOS3I2CmHgVXwMj5JU2FwQmn3Tm1w


{
  "clock": {
    "time": "2023-10-24T16:13:18+0100",
    "status": true
  }
}

### Get by user id
GET http://localhost:4000/api/clocks/1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0aW1lX21hbmFnZXIiLCJleHAiOjE3MDExNjk5MzEsImlhdCI6MTY5ODc1MDczMSwiaXNzIjoidGltZV9tYW5hZ2VyIiwianRpIjoiYmEwZGQxZGEtZDg4NC00MDYyLWFjYWUtYTA2MmUyYTg4MWEyIiwibmJmIjoxNjk4NzUwNzMwLCJzdWIiOiIyMSIsInR5cCI6ImFjY2VzcyJ9.pQxCZlhfm735SblAzwob1kQXqMNKL234BxBE0cu5_Fajd3YbNLo77MK5IOOS3I2CmHgVXwMj5JU2FwQmn3Tm1w


