### Add Users (Check required)
POST http://localhost:4000/api/users
Content-Type: application/json

{
  "user": {
  }
}

### Add Users (Check string)
POST http://localhost:4000/api/users
Content-Type: application/json

{
  "user": {
    "username": 1,
    "email": 1
  }
}

### Add User employee
POST http://localhost:4000/api/users
Content-Type: application/json

{
  "user": {
    "username": "john",
    "email": "john.doe2@gmail.com",
    "role": "employee"
  }
}

### Add User manager
POST http://localhost:4000/api/users
Content-Type: application/json

{
  "user": {
    "username": "jane",
    "email": "jane.doe@gmail.com",
    "role": "manager"
  }
}

### Add User general manager
POST http://localhost:4000/api/users
Content-Type: application/json

{
  "user": {
    "username": "ben",
    "email": "ben.doe@gmail.com",
    "role": "general_manager"
  }
}

### Update user
PUT http://localhost:4000/api/users/1
Content-Type: application/json

{
  "user": {
    "username": "john01",
    "email": "john01.doe@gmail.com",
    "role": "manager"
  }
}

### Get all
GET http://localhost:4000/api/users

### Get by id
GET http://localhost:4000/api/users/1

### Get by email and username
GET  http://localhost:4000/api/users?email=john.doe@gmail.com&username=john

### Delete user
DELETE http://localhost:4000/api/users/1