### Add User 1 in Team 1
POST http://localhost:4000/api/teams/1/1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0aW1lX21hbmFnZXIiLCJleHAiOjE3MDE0MjQzMzksImlhdCI6MTY5OTAwNTEzOSwiaXNzIjoidGltZV9tYW5hZ2VyIiwianRpIjoiM2Y2NjFiYzAtNzBkYS00MTdhLWIwYTQtNjA5MzZjMzMyNDgyIiwibmJmIjoxNjk5MDA1MTM4LCJzdWIiOiIxIiwidHlwIjoiYWNjZXNzIn0.BroOOSmMPkgxn32Frs0xps07MOLAg3bJZcy-Dg1yb8Wp1MZaU9O-9WIM_4ETGy5njPfMHExJID0p1NilHj_Eqg
