### Add Workingtimes (Check required)
POST http://localhost:4000/api/workingtimes/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0aW1lX21hbmFnZXIiLCJleHAiOjE3MDExNjk5MzEsImlhdCI6MTY5ODc1MDczMSwiaXNzIjoidGltZV9tYW5hZ2VyIiwianRpIjoiYmEwZGQxZGEtZDg4NC00MDYyLWFjYWUtYTA2MmUyYTg4MWEyIiwibmJmIjoxNjk4NzUwNzMwLCJzdWIiOiIyMSIsInR5cCI6ImFjY2VzcyJ9.pQxCZlhfm735SblAzwob1kQXqMNKL234BxBE0cu5_Fajd3YbNLo77MK5IOOS3I2CmHgVXwMj5JU2FwQmn3Tm1w


{
  "workingtime": {
  }
}

### Add Workingtimes (Check formart)
POST http://localhost:4000/api/workingtimes/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0aW1lX21hbmFnZXIiLCJleHAiOjE3MDExNjk5MzEsImlhdCI6MTY5ODc1MDczMSwiaXNzIjoidGltZV9tYW5hZ2VyIiwianRpIjoiYmEwZGQxZGEtZDg4NC00MDYyLWFjYWUtYTA2MmUyYTg4MWEyIiwibmJmIjoxNjk4NzUwNzMwLCJzdWIiOiIyMSIsInR5cCI6ImFjY2VzcyJ9.pQxCZlhfm735SblAzwob1kQXqMNKL234BxBE0cu5_Fajd3YbNLo77MK5IOOS3I2CmHgVXwMj5JU2FwQmn3Tm1w


{
  "workingtime": {
    "start": 1,
    "end": 1
  }
}


### Add Workingtimes
POST http://localhost:4000/api/workingtimes/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0aW1lX21hbmFnZXIiLCJleHAiOjE3MDE0MjYxODcsImlhdCI6MTY5OTAwNjk4NywiaXNzIjoidGltZV9tYW5hZ2VyIiwianRpIjoiMGFhNGUwNzctODJhMC00ZmI4LWIyMDQtZTcxNzdjMWU0Y2YyIiwibmJmIjoxNjk5MDA2OTg2LCJzdWIiOiIxIiwidHlwIjoiYWNjZXNzIn0.hnl5QObfTDeIkBYoFPPk-D67XDLI94k-hG7U0TV5QQFAzOJ36znz2p9oe4tmG5e4mbpCnB8Bt58Ey02t_eSYDw

{
"workingtime": {
  "start": "2023-10-06 06:50:40Z",
  "end": "2023-10-07 19:20:52Z"
}
}


### delete Workingtimes
DELETE http://localhost:4000/api/workingtimes/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0aW1lX21hbmFnZXIiLCJleHAiOjE3MDE0MjYxODcsImlhdCI6MTY5OTAwNjk4NywiaXNzIjoidGltZV9tYW5hZ2VyIiwianRpIjoiMGFhNGUwNzctODJhMC00ZmI4LWIyMDQtZTcxNzdjMWU0Y2YyIiwibmJmIjoxNjk5MDA2OTg2LCJzdWIiOiIxIiwidHlwIjoiYWNjZXNzIn0.hnl5QObfTDeIkBYoFPPk-D67XDLI94k-hG7U0TV5QQFAzOJ36znz2p9oe4tmG5e4mbpCnB8Bt58Ey02t_eSYDw



### update Workingtimes
PUT http://localhost:4000/api/workingtimes/10
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0aW1lX21hbmFnZXIiLCJleHAiOjE3MDExNjk5MzEsImlhdCI6MTY5ODc1MDczMSwiaXNzIjoidGltZV9tYW5hZ2VyIiwianRpIjoiYmEwZGQxZGEtZDg4NC00MDYyLWFjYWUtYTA2MmUyYTg4MWEyIiwibmJmIjoxNjk4NzUwNzMwLCJzdWIiOiIyMSIsInR5cCI6ImFjY2VzcyJ9.pQxCZlhfm735SblAzwob1kQXqMNKL234BxBE0cu5_Fajd3YbNLo77MK5IOOS3I2CmHgVXwMj5JU2FwQmn3Tm1w


{
  "workingtime": {
    "start": "2023-11-25 16:30",
    "end": "2023-12-01 16:00"
  }
}

### show one Workingtimes
GET http://localhost:4000/api/workingtimes/1/1

### show all Workingtimes
GET http://localhost:4000/api/workingtimes/1?start=2021-10-25 00:30:45Z&end=2026-01-01 00:00:45Z
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0aW1lX21hbmFnZXIiLCJleHAiOjE3MDE0MjYxODcsImlhdCI6MTY5OTAwNjk4NywiaXNzIjoidGltZV9tYW5hZ2VyIiwianRpIjoiMGFhNGUwNzctODJhMC00ZmI4LWIyMDQtZTcxNzdjMWU0Y2YyIiwibmJmIjoxNjk5MDA2OTg2LCJzdWIiOiIxIiwidHlwIjoiYWNjZXNzIn0.hnl5QObfTDeIkBYoFPPk-D67XDLI94k-hG7U0TV5QQFAzOJ36znz2p9oe4tmG5e4mbpCnB8Bt58Ey02t_eSYDw
