name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Repository via HTTPS
        run: git clone https://github.com/AbrahamDiaw/timemanager_app.git

      - name: SSH into AWS EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker.io docker-compose
            sudo docker compose -f timemanager_app/docker-compose.yml up -d
            sudo docker compose -f timemanager_app/docker-compose.yml ps

      - name: Deployed to EC2 Succes
        run: |
          echo "Déploiement terminé avec succès !"
