name: Time manager deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/setup-aws-cli@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to AWS ECR
        run: aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 412477988425.dkr.ecr.eu-north-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
        working-directory: /

      - name: Configure AWS Elastic Beanstalk
        run: |
          eb init -p docker Timemanagerapp-env
          eb use Timemanagerapp-env
          eb deploy

      - name: Deployed to Elastic Beanstalk
