name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and Push Docker images with Docker Compose
        run: |
          docker-compose -f ${{ github.workspace }}/docker-compose.yml build
          docker-compose -f ${{ github.workspace }}/docker-compose.yml push timemanager_app_client:latest
          docker-compose -f ${{ github.workspace }}/docker-compose.yml push timemanager_app_server:latest
          docker-compose -f ${{ github.workspace }}/docker-compose.yml push timemanager_app_db:latest
