name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

     # - name: Build the Docker image
      #  run: docker build -t abrhmdiaw/time_manager_cicd .

        #- name: Push to Dockerhub
        #run: docker push abrhmdiaw/time_manager_cicd:latest

      - name: Build and Push Docker images with Docker Compose
        run: docker-compose -f ${{ github.workspace }}/docker-compose.yml build

      - name: Push to Dockerhub
        run: | 
          docker-compose -f ${{ github.workspace }}/docker-compose.yml push
          docker push abrhmdiaw/time_manager_cicd:tagname

