name: Ci Cd EC2

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute remote SSH commands
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2_private_key.pem
          chmod 600 ec2_private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          ssh -i ec2_private_key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "echo 'hello'"
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: Build Docker container
        run: |
          sudo docker-compose -f timemanager_app/docker-compose.yml up -d
          sudo docker-compose -f timemanager_app/docker-compose.yml ps

      - name: Deployed to EC2 Success
        run: |
          echo "Déploiement terminé avec succès !"
