name: Ci Cd EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH REMOTE INSTANCE, INSTALL DOCKER, BUILD AND DEPLOY
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2_private_key.pem
          chmod 600 ec2_private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
          ssh -i ec2_private_key.pem ubuntu@${{ secrets.EC2_HOST }} '
            git clone https://github.com/AbrahamDiaw/timemanager_app.git
            ls -la
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
            sudo docker-compose -f timemanager_app/docker-compose.yml up -d
            sudo docker-compose -f timemanager_app/docker-compose.yml ps
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Deployed to EC2 Success
        run: |
          echo "Déploiement terminé avec succès !"
